### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by erlingrj** [erlingrj/reactor-uc#51]
It is overdue to implement a logging system. I want it to be simple but flexible. I want
- Specify logging of arbitrary "modules" with e.g. `LOG_REGISTER_MODULE("scheduler")`
- Set verbosity level for each module `LOG_LEVEL("scheduler", LOG_INFO)`
- Set verbosity level for all modules in one go.
- Do logging specific to each module `LOG_ERR("scheduler", "Tried to schedule event into the past %ld", event_time);`

Zephyr has a particularly nice logging system and I want our logging to match nicely to that: https://docs.zephyrproject.org/latest/services/logging/index.html

For other targets we can chose to either:
1. Implement the nice logging system with multiple modules or
2. Just check global verbosity level and dump everything out over printf.

**Comment by tanneberger** [comment]
@LasseRosenow is there a nice riot-os logging module the only thing I found is:
https://doc.riot-os.org/core_2lib_2include_2log_8h.html

**Comment by erlingrj** [comment]
I am looking at this currently :)

**Comment by LasseRosenow** [comment]
> @LasseRosenow is there a nice riot-os logging module the only thing I found is: https://doc.riot-os.org/core_2lib_2include_2log_8h.html

From my knowledge in RIOT it is common to just use printf and then hide Debug prints behind the DEBUG define, which can be overwritten on a per-file basis.

This logging system that you are referencing there is the better alternative to that in my view, but usage of it is somewhat "random".

**Comment by erlingrj** [comment]
A first iteration of flexible logging system is now in main
